### ISSUE TITLE
The performance of pre-train with ROS on PVRCNN from Waymo->KITTI

### ISSUE THREAD

**Issue by KevinDuBl** [CVMI-Lab/ST3D#43] opened 2022-05-24 07:19 UTC
I got 19.27 for moderate AP3D with IOU threshold 0.7 on car category on PVRCNN with ROS from Waymo->KITTI, which is worse than the performance of that on PVRCNN without ROS shown in the paper(22.01). Then I trained the PVRCNN without ROS on my machine, and got the best result over 22 on epoch. I used the original config on cfgs/da-waymo-kitti_models/pvrcnn/ pvrcnn_old_anchor.yaml and cfgs/da-waymo-kitti_models/pvrcnn/ pvrcnn_old_anchor_ros.yaml, did I do something wrong? And did you also get the unstable result on Waymo->KITTI?

**Comment by jihanyang** [comment] 2022-05-24 12:42
Actually, there are some unstable results on Waymo-> KITTI, however, it should be around 1~2\%. You can send me an email to request the pertrained model to first to verify correct environment setups by validate the model in your machine.  The performance of PVRCNN with ROS should at least higher than 54% AP3D @0.7 (I don't remeber it for sure).

**Comment by KevinDuBl** [comment] 2022-05-24 15:54
Thank you! The A100 on my machine only support CUDA11 and pcdet0.5+. So I installed the spconv1.0 manually and setup the pcdet0.5, then copied the cuda operators under the file ops to file ST3D/ops. After that I can start training. But there are some bugs on pre-train and self-train, I fixed them. How could I do to request for the pertrained model?

**Comment by KevinDuBl** [comment] 2022-05-24 16:04
There are some bugs when runing this code, I found that the ROS is disabled in cfgs/da-waymo-kitti_models/pvrcnn/pvrcnn_old_anchor_ros.yaml in pre-train on Waymo, am I right? Is this the code you used for experiment in ST3D paper?

**Comment by jihanyang** [comment] 2022-05-25 02:33
No, the ROS is not disabled. Please check carefully.
https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/tools/cfgs/da-waymo-kitti_models/pvrcnn/pvrcnn_old_anchor_ros.yaml#L18-L19

**Comment by jihanyang** [comment] 2022-05-25 02:35
@KevinDuBl Just send me an email. I guess your poor performance might be caused by the environment issue, I will come to fix that recently.

**Comment by KevinDuBl** [comment] 2022-05-25 02:42
> No, the ROS is not disabled. Please check carefully.
> 
> https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/tools/cfgs/da-waymo-kitti_models/pvrcnn/pvrcnn_old_anchor_ros.yaml#L18-L19

The ROS on the target dataset(KITTI) is not disabled, but ROS on the source dataset(Waymo) is disabled. According to the paper, the pre-train is trained only on the source dataset(Waymo), which don't use the ROS. Is that correct?

**Comment by KevinDuBl** [comment] 2022-05-25 03:08
> No, the ROS is not disabled. Please check carefully.
> 
> https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/tools/cfgs/da-waymo-kitti_models/pvrcnn/pvrcnn_old_anchor_ros.yaml#L18-L19

https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/tools/cfgs/da-waymo-kitti_models/pvrcnn/pvrcnn_old_anchor_ros.yaml#L4
The data augment config of source domain is refer to 'cfgs/dataset_configs/da_waymo_dataset.yaml' , but in this file, the ROS is disabled.
https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/tools/cfgs/dataset_configs/da_waymo_dataset.yaml#L21

**Comment by jihanyang** [comment] 2022-05-25 06:37
Those items will be rewirted. You can try by yourself.

**Comment by KevinDuBl** [comment] 2022-05-25 06:45
You mean what I think is right? Is the ROS disabled in pre-train of this task? I want to confirm this so that I can fix it by myself, thank you！

**Comment by jihanyang** [comment] 2022-05-25 12:10
No. I mean you are wrong. Those lines highlighted by me already replace those terms in the da_waymo_dataset.yaml.

**Comment by KevinDuBl** [comment] 2022-05-25 12:45
The lines highlighted by you is only the augmentor for the target dataset(KITTI). The ROS is disabled for the source dataset(Waymo) is disabled in disabled in https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/tools/cfgs/dataset_configs/da_waymo_dataset.yaml#L21
And the experiment result also shows this. This is the info of your config:
![image](https://user-images.githubusercontent.com/20028640/170263999-644a4891-26b9-47d1-82c7-11d80de5212d.png)
![image](https://user-images.githubusercontent.com/20028640/170264165-0c8452a8-0d32-4bcf-b8bf-b12db658c725.png)
The car AP3D result of PVRCNN with ROS under your config is a little worse than 22.01.
When I modify the config and enable the ROS on source dataset(Waymo), I got this:
![image](https://user-images.githubusercontent.com/20028640/170264948-822761e1-b590-4b7e-a9bc-4dc3ba33fcb3.png)
And the result of my config is 0.54.

**Comment by jihanyang** [comment] 2022-05-25 13:06
Oh, sorry I notice that. I place the data augmentation config in error place. Very appreciate for your feedback! I will modify it intermidately.

**Comment by KevinDuBl** [comment] 2022-05-25 14:16
Thank you very much!

**Comment by KevinDuBl** [comment] 2022-05-30 03:35
I trained the cfgs/da-waymo-kitti_models/pvrcnn/pvrcnn_old_anchor_sn.yaml and got the AP3D 58%, which is lower than the 76.86% in the paper. Could you please give me the SN 'SIZE_RES' you used in your experiment?

**Comment by jihanyang** [comment] 2022-05-31 01:44
Notice that you just train SN, rather than ST3D (w/ SN). Please see GETTING_START carefully to finish the training.

**Comment by KevinDuBl** [comment] 2022-06-08 06:41
Excuse me, what does the config 'SHIFT_COOR' mean? How to choose the proper 'SHIFT_COOR'?

**Comment by jihanyang** [comment] 2022-06-10 03:01
I have explained this keyword in previous issues. I guess that could help you. I would close this issue since the major problem have been solved. Thank you for your feedback, and feel free to re-open.

**Closed by jihanyang** 2022-06-10 03:01 UTC
